#:kivy 1.9.0
# File name: IDK.kv
<ApplicationView>:
    stockList: stockList
    userInputs: userInputs
    currentStock: currentStock
    # currentInfo: currentInfo
    orientation: 'horizontal'

    BoxLayout:
        orientation: 'vertical'
        size_hint_x: 0.45
        TextInput:
            font_size: 25
            size_hint_y: None
            height: 43
            hint_text: 'Search'
        ScrollView:
            GridLayout:
                id: stockList
                cols: 1
                size_hint_y: None
                size_hint_x: 1
                height: self.minimum_height

    BoxLayout:
        orientation: 'vertical'
        size_hint_x: 0.55

        Label:
            id: currentStock
            size_hint: 1, None
            height: 42
            font_size: 25
            text: 'No Selected Stock'
            color: 0, 0, 0, 1
            canvas.before:
                Color:
                    rgba: 0.9, 0.9, 0.9, 1
                Rectangle:
                    pos: self.pos
                    size: self.size
                Color:
                    rgba: 0, 0, 0, 1  # black
                Line:
                    rectangle: (self.x, self.y, self.width, self.height)
                    width: 2
        ScrollView:
            GridLayout:
                id: userInputs
                cols: 1
                size_hint_y: None
                spacing: 5
                height: self.minimum_height
                # Label:
                #     id: currentInfo
                #     size_hint_y: None
                #     height: 60
                #     font_size: 20
                #     markup: True
                #     text: 'Current Info Given\n\n'            
        Label:
            size_hint_y: None
            height: 30
            text: 'VAR:'
            font_size: 25
