#:kivy 1.9.0
# File name: IDK.kv
<ApplicationView>:
    stockList: stockList
    userInputs: userInputs
    currentStock: currentStock
    valAtRisk: valAtRisk
    orientation: 'horizontal'

    BoxLayout:
        orientation: 'vertical'
        size_hint_x: 0.45
        # TextInput:
        #     font_size: 25
        #     size_hint_y: None
        #     height: 43
        #     hint_text: 'Search'
        Label:
            font_size: 25
            size_hint_y: None
            height: 43
            text: 'Stock List: FTSE100'
            canvas.before:
                Color:
                    rgba: 0.2, 0.2, 0.2, 1
                Rectangle:
                    pos: self.pos
                    size: self.size
                Color:
                    rgba: 0, 0, 0, 1 
                Line:
                    rectangle: (self.x, self.y, self.width, self.height)
                    width: 1.5
        ScrollView:
            GridLayout:
                id: stockList
                cols: 1
                size_hint_y: None
                size_hint_x: 1
                height: self.minimum_height

    BoxLayout:
        orientation: 'vertical'
        size_hint_x: 0.55
        Label:
            id: currentStock
            size_hint: 1, None
            height: 43
            font_size: 30
            text: 'No Selected Stock'
            color: 0, 0, 0, 1
            canvas.before:
                Color:
                    rgba: 0.9, 0.9, 0.9, 1
                Rectangle:
                    pos: self.pos
                    size: self.size
                Color:
                    rgba: 0, 0, 0, 1 
                Line:
                    rectangle: (self.x, self.y, self.width, self.height)
                    width: 1.5

        GridLayout:
            id: userInputs
            cols: 1
            size_hint_y: None
            spacing: 5
            height: 427
            canvas.before:
                Color:
                    rgba: 0.5, 0.5, 0.5, 1
                Rectangle:
                    pos: self.pos
                    size: self.size
                Color:
                    rgba: 0, 0, 0, 1 
                Line:
                    rectangle: (self.x, self.y, self.width, self.height)
                    width: 1.5
        
        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: None
            height: 30
            Button:
                size_hint_x: 0.3
                text: 'Generate'
                font_size: 25
                on_press: root.generateVaR()        
            Label:
                id: valAtRisk
                size_hint_x: 0.7
                text: ' VaR: '
                font_size: 25
                halign: 'left'
                valign: 'middle'
                text_size: self.size

